name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: tts_openai_rust-linux-x86_64.tar.gz
          - os: ubuntu-latest
            artifact_name: tts_openai_rust-linux-arm64.tar.gz
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: tts_openai_rust-macos-x86_64.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Compress artifact
        run: tar -czvf ${{ matrix.artifact_name }} target/release/tts_openai_rust
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
