name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-22.04
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: macos-14
            arch: x64
          - os: windows-latest
            arch: x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zstd
      uses: ConorMacBride/install-package@v1
      with:
        apt: zstd
        brew: zstd
        choco: zstandard

    - name: Archive contents
      run: |
        tar -c ./* | zstd -z -o results.tar.zst
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: repo-contents-${{ matrix.os }}-${{ matrix.arch }}
        path: results.tar.zst
