name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        libc: [gnu, musl]
        include:
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64
            libc: gnu
          - os: ubuntu-latest
            arch: x64
            libc: gnu
          - os: ubuntu-latest
            arch: arm64
            libc: gnu
          - os: ubuntu-latest
            arch: x64
            libc: musl
          - os: ubuntu-latest
            arch: arm64
            libc: musl

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run tests
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          python -m unittest discover
        else
          python3 -m unittest discover
